/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AsJ77WQuLhg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/main/components/ui/select"
import { CardContent, Card } from "@/main/components/ui/card"
import { Input } from "@/main/components/ui/input"
import { Button } from "@/main/components/ui/button"

export function RedVelvet() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-50">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b border-gray-200 dark:border-gray-700">
        <Link className="flex items-center justify-center" href="#">
          <Music2Icon className="h-6 w-6 text-red-500 dark:text-red-400" />
          <span className="sr-only">Music Drives</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:text-red-500 dark:hover:text-red-400" href="#">
            Features
          </Link>
          <Link className="text-sm font-medium hover:text-red-500 dark:hover:text-red-400" href="#">
            Testimonials
          </Link>
          <Link className="text-sm font-medium hover:text-red-500 dark:hover:text-red-400" href="#">
            Buy
          </Link>
          <Select value="dark">
            <SelectTrigger className="w-[100px]">
              <SelectValue placeholder="Theme" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="light">Light</SelectItem>
              <SelectItem value="dark">Dark</SelectItem>
            </SelectContent>
          </Select>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-red-500 to-red-600 dark:from-red-600 dark:to-red-700">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter text-white sm:text-5xl md:text-6xl">
                Unleash Your Music with Our Powerful Flash Drives
              </h1>
              <p className="max-w-[600px] text-gray-200 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Experience the ultimate in music storage and portability with our high-quality flash drives. Designed
                for music enthusiasts, our drives offer unparalleled performance and reliability.
              </p>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-white px-8 text-sm font-medium text-red-600 shadow transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-950 dark:text-gray-50 dark:hover:bg-gray-800 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Buy Now
              </Link>
            </div>
            <img
              alt="Music Flash Drive"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
              height="400"
              src="/placeholder.svg"
              width="400"
            />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <img
              alt="Music Flash Drive Features"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
              height="400"
              src="/placeholder.svg"
              width="400"
            />
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-red-100 px-3 py-1 text-sm dark:bg-red-900">Features</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Unparalleled Storage and Performance
              </h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our music flash drives offer lightning-fast data transfer speeds, ample storage capacity, and
                uncompromising durability. Elevate your music experience with our cutting-edge technology.
              </p>
              <ul className="grid gap-2">
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 text-red-500 dark:text-red-400" />
                  High-speed data transfer
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 text-red-500 dark:text-red-400" />
                  Massive storage capacity
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 text-red-500 dark:text-red-400" />
                  Durable and reliable
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <div className="inline-block rounded-lg bg-red-100 px-3 py-1 text-sm dark:bg-red-900">Testimonials</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Customers Say</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Hear from our satisfied customers and see why they love our music flash drives.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
              <Card className="bg-white dark:bg-gray-950 dark:border-gray-800">
                <CardContent className="space-y-4">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Avatar"
                      className="h-10 w-10 rounded-full"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "40/40",
                        objectFit: "cover",
                      }}
                      width="40"
                    />
                    <div>
                      <h3 className="text-sm font-semibold">John Doe</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">Music Producer</p>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    "These music flash drives are a game-changer! The speed and\n storage capacity are unbeatable. I can
                    now store all my\n music projects with ease."
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-white dark:bg-gray-950 dark:border-gray-800">
                <CardContent className="space-y-4">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Avatar"
                      className="h-10 w-10 rounded-full"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "40/40",
                        objectFit: "cover",
                      }}
                      width="40"
                    />
                    <div>
                      <h3 className="text-sm font-semibold">Jane Smith</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">DJ</p>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    "I've been using these flash drives for my DJ sets, and\n they've been a lifesaver. The reliability
                    and durability are\n unmatched."
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-white dark:bg-gray-950 dark:border-gray-800">
                <CardContent className="space-y-4">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Avatar"
                      className="h-10 w-10 rounded-full"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "40/40",
                        objectFit: "cover",
                      }}
                      width="40"
                    />
                    <div>
                      <h3 className="text-sm font-semibold">Michael Johnson</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">Musician</p>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    "These music flash drives have completely transformed my\n workflow. The seamless integration and
                    lightning-fast\n performance are unparalleled."
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <div className="inline-block rounded-lg bg-red-100 px-3 py-1 text-sm dark:bg-red-900">Buy Now</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Get Your Music Flash Drive Today
              </h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Order your high-performance music flash drive and take your music experience to the next level.
              </p>
            </div>
            <form className="mx-auto w-full max-w-sm space-y-2">
              <div className="flex space-x-2">
                <Input className="max-w-lg flex-1" placeholder="Name" type="text" />
                <Input className="max-w-lg flex-1" placeholder="Email" type="email" />
              </div>
              <Input className="max-w-lg flex-1" placeholder="Address" type="text" />
              <Button className="w-full" type="submit">
                Order Now
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-gray-200 dark:border-gray-700">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Music Drives. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:text-red-500 dark:hover:text-red-400" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:text-red-500 dark:hover:text-red-400" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function Music2Icon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="18" r="4" />
      <path d="M12 18V2l7 4" />
    </svg>
  )
}
