/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dxDSysK0f7D
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/main/components/ui/avatar"
import { Input } from "@/main/components/ui/input"
import { Textarea } from "@/main/components/ui/textarea"
import { Button } from "@/main/components/ui/button"
import Image from "next/image"
import dua from "@/main/assets/2.jpg"

export function Sandisk() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-gray-900 text-white dark:bg-gray-900 dark:text-white">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6 text-red-500" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:text-red-500 transition-colors" href="#">
            Products
          </Link>
          <Link className="text-sm font-medium hover:text-red-500 transition-colors" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:text-red-500 transition-colors" href="#">
            Testimonials
          </Link>
          <Link className="text-sm font-medium hover:text-red-500 transition-colors" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-gray-900 to-black dark:from-gray-900 dark:to-black">
          <div className="container px-4 md:px-6 space-y-6 md:space-y-10">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem] text-red-500">
                  {/* Elevate Your Business with Our Solutions */}
                  Ribuan Lagu & Video Dalam 1 Flashdisk
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-300 md:text-xl dark:text-gray-400">
                  Hadirkan Hiburan Tanpa Batas pada Perjalanan Anda dengan Flashdisk Hiburan Mobil Terbaik!
                </p>
                <div className="mt-6">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-red-500 px-8 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-red-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-red-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-red-400 dark:text-gray-900 dark:hover:bg-red-500 dark:focus-visible:ring-red-600"
                    href="#"
                  >
                    Pesan Sekarang
                  </Link>
                </div>
              </div>
              <div className="hidden md:block">
                <img
                  alt="Hero"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
                  height="550"
                  src="/placeholder.svg"
                  width="550"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-800 dark:bg-gray-800">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-red-500">
                  Produk dan Layanan Kami
                </h2>
                <p className="max-w-[900px] text-gray-300 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Dapatkan Flashdisk Hiburan Terbaik untuk Mobil Anda dan nikmati perjalanan yang lebih menyenangkan.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <img
                  alt="Product 1"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
                  height="200"
                  src="/placeholder.svg"
                  width="300"
                />
                <h3 className="text-lg font-bold text-red-500">Product 1</h3>
                <p className="text-sm text-gray-300 dark:text-gray-400">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
              </div>
              <div className="grid gap-1">
                <img
                  alt="Product 2"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
                  height="200"
                  src="/placeholder.svg"
                  width="300"
                />
                <h3 className="text-lg font-bold text-red-500">Product 2</h3>
                <p className="text-sm text-gray-300 dark:text-gray-400">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
              </div>
              <div className="grid gap-1">
                <img
                  alt="Service 1"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
                  height="200"
                  src="/placeholder.svg"
                  width="300"
                />
                <h3 className="text-lg font-bold text-red-500">Service 1</h3>
                <p className="text-sm text-gray-300 dark:text-gray-400">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-950">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-red-500 px-3 py-1 text-sm text-gray-950">Testimonials</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-red-500">What our customers say</h2>
                <p className="max-w-[900px] text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Hear from the people who love using our platform to build their web applications.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-4">
                  <div className="flex flex-col items-start gap-2 rounded-lg bg-gray-900 p-4 shadow-lg">
                    <div className="flex items-center gap-2">
                      <img
                        alt="Avatar"
                        className="h-10 w-10 rounded-full"
                        height="40"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "40/40",
                          objectFit: "cover",
                        }}
                        width="40"
                      />
                      <div>
                        <h3 className="text-lg font-semibold">John Doe</h3>
                        <p className="text-sm text-gray-400">CEO, Acme Inc</p>
                      </div>
                    </div>
                    <p className="text-gray-400">
                      "Vercel has been a game-changer for our team. The\n platform's ease of use and powerful features
                      have\n allowed us to build and deploy our web applications\n faster than ever before."
                    </p>
                    <div className="mt-2 rounded-lg border border-slate-200 border-gray-800 dark:border-slate-800">
                      <img
                        alt="Screenshot"
                        className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                        height="310"
                        src="/placeholder.svg"
                        width="550"
                      />
                    </div>
                  </div>
                  <div className="flex flex-col items-start gap-2 rounded-lg bg-gray-900 p-4 shadow-lg">
                    <div className="flex items-center gap-2">
                      <img
                        alt="Avatar"
                        className="h-10 w-10 rounded-full"
                        height="40"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "40/40",
                          objectFit: "cover",
                        }}
                        width="40"
                      />
                      <div>
                        <h3 className="text-lg font-semibold">Jane Smith</h3>
                        <p className="text-sm text-gray-400">Lead Developer, Acme Inc</p>
                      </div>
                    </div>
                    <p className="text-gray-400">
                      "Vercel's powerful features and seamless integration with\n our development workflow have been a
                      game-changer for\n our team. We're able to focus on building great\n experiences instead of
                      worrying about infrastructure."
                    </p>
                    <div className="mt-2 rounded-lg border border-slate-200 border-gray-800 dark:border-slate-800">
                      <img
                        alt="Screenshot"
                        className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                        height="310"
                        src="/placeholder.svg"
                        width="550"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-4">
                  <div className="flex flex-col items-start gap-2 rounded-lg bg-gray-900 p-4 shadow-lg">
                    <div className="flex items-center gap-2">
                      <img
                        alt="Avatar"
                        className="h-10 w-10 rounded-full"
                        height="40"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "40/40",
                          objectFit: "cover",
                        }}
                        width="40"
                      />
                      <div>
                        <h3 className="text-lg font-semibold">Bob Johnson</h3>
                        <p className="text-sm text-gray-400">Product Manager, Acme Inc</p>
                      </div>
                    </div>
                    <p className="text-gray-400">
                      "Vercel's platform has been a game-changer for our\n product team. The ability to quickly deploy
                      and iterate\n on our web applications has allowed us to deliver\n features faster than ever
                      before."
                    </p>
                    <div className="mt-2 rounded-lg border border-slate-200 border-gray-800 dark:border-slate-800">
                      <img
                        alt="Screenshot"
                        className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                        height="310"
                        src="/placeholder.svg"
                        width="550"
                      />
                    </div>
                  </div>
                  <div className="flex flex-col items-start gap-2 rounded-lg bg-gray-900 p-4 shadow-lg">
                    <div className="flex items-center gap-2">
                      <img
                        alt="Avatar"
                        className="h-10 w-10 rounded-full"
                        height="40"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "40/40",
                          objectFit: "cover",
                        }}
                        width="40"
                      />
                      <div>
                        <h3 className="text-lg font-semibold">Sarah Lee</h3>
                        <p className="text-sm text-gray-400">Designer, Acme Inc</p>
                      </div>
                    </div>
                    <p className="text-gray-400">
                      "Vercel's platform has been a game-changer for our\n design team. The ability to quickly preview
                      and deploy\n our designs has allowed us to collaborate more\n effectively with our development
                      team."
                    </p>
                    <div className="mt-2 rounded-lg border border-slate-200 border-gray-800 dark:border-slate-800">
                      <img
                        alt="Screenshot"
                        className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                        height="310"
                        src="/placeholder.svg"
                        width="550"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-900 dark:bg-gray-900">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-red-500">What Our Customers Say</h2>
                <p className="max-w-[900px] text-gray-300 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Hear from our satisfied customers and learn how our solutions have helped their businesses.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1 bg-gray-800 dark:bg-gray-800 p-4 rounded-lg">
                <blockquote>
                  <p className="text-sm text-gray-300 dark:text-gray-400">
                    "Working with Acme Inc has been a game-changer for our\n business. Their products and services have
                    helped us\n streamline our operations and drive growth."
                  </p>
                </blockquote>
                <div className="flex items-center space-x-4 mt-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-avatar.svg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-sm font-semibold text-red-500">John Doe</h4>
                    <p className="text-sm text-gray-300 dark:text-gray-400">CEO, Acme Corp</p>
                  </div>
                </div>
              </div>
              <div className="grid gap-1 bg-gray-800 dark:bg-gray-800 p-4 rounded-lg">
                <blockquote>
                  <p className="text-sm text-gray-300 dark:text-gray-400">
                    "Acme Inc's solutions have been a game-changer for our\n business. Their team has been incredibly
                    helpful and\n responsive throughout the process."
                  </p>
                </blockquote>
                <div className="flex items-center space-x-4 mt-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-avatar.svg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-sm font-semibold text-red-500">Jane Smith</h4>
                    <p className="text-sm text-gray-300 dark:text-gray-400">COO, Acme Corp</p>
                  </div>
                </div>
              </div>
              <div className="grid gap-1 bg-gray-800 dark:bg-gray-800 p-4 rounded-lg">
                <blockquote>
                  <p className="text-sm text-gray-300 dark:text-gray-400">
                    "I highly recommend Acme Inc to any business looking to\n take their operations to the next level.
                    Their products\n and services are top-notch."
                  </p>
                </blockquote>
                <div className="flex items-center space-x-4 mt-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-avatar.svg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-sm font-semibold text-red-500">Bob Johnson</h4>
                    <p className="text-sm text-gray-300 dark:text-gray-400">CTO, Acme Corp</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-800 dark:bg-gray-800">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-red-500">Get in Touch</h2>
                <p className="max-w-[900px] text-gray-300 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Fill out the form below to learn more about our products and services, or to schedule a consultation.
                </p>
              </div>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col space-y-4">
                <Input className="max-w-lg flex-1" placeholder="Name" type="text" />
                <Input className="max-w-lg flex-1" placeholder="Email" type="email" />
                <Textarea className="max-w-lg flex-1" placeholder="Message" />
                <Button className="bg-red-500 hover:bg-red-600 text-gray-900" type="submit">
                  Submit
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-gray-800 dark:border-gray-800">
        <p className="text-xs text-gray-400 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:text-red-500 transition-colors dark:hover:text-red-500" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:text-red-500 transition-colors dark:hover:text-red-500" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
