/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/G09f7BmVqcJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Gabarito } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/main/components/ui/select"
import { CardContent, Card } from "@/main/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/main/components/ui/carousel"

export function Sebration() {
  return (
    <div className="flex flex-col min-h-[100dvh] dark:bg-gray-900 dark:text-gray-50">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-gray-900 dark:bg-gray-950">
        <Link className="flex items-center justify-center" href="#">
          <Music2Icon className="h-6 w-6 text-red-500" />
          <span className="sr-only">Music Drives</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 text-gray-50 dark:text-gray-400"
            href="#"
          >
            Features
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 text-gray-50 dark:text-gray-400"
            href="#"
          >
            Pricing
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 text-gray-50 dark:text-gray-400"
            href="#"
          >
            Testimonials
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 text-gray-50 dark:text-gray-400"
            href="#"
          >
            Contact
          </Link>
          <Select defaultValue="light">
            <SelectTrigger className="w-[100px]">
              <SelectValue placeholder="Theme" />
              <ChevronDownIcon className="h-4 w-4" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="light">Light</SelectItem>
              <SelectItem value="dark">Dark</SelectItem>
            </SelectContent>
          </Select>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-900 dark:bg-gray-950">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter text-gray-50 sm:text-5xl xl:text-6xl/none">
                    Elevate Your Music Experience
                  </h1>
                  <p className="max-w-[600px] text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Discover the ultimate in portable music storage with our high-quality music flash drives.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-red-500 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-red-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-red-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-red-400 dark:text-gray-900 dark:hover:bg-red-500 dark:focus-visible:ring-red-300"
                    href="#"
                  >
                    Buy Now
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-slate-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-slate-800"
                    href="#"
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <img
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
                height="550"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-red-500 px-3 py-1 text-sm text-gray-50 dark:bg-red-400 dark:text-gray-900">
                  Key Features
                </div>
                <h2 className="text-3xl font-bold tracking-tighter text-gray-900 sm:text-5xl dark:text-gray-50">
                  Unleash the Power of Your Music
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Our music flash drives offer unparalleled storage, lightning-fast transfer speeds, and a sleek,
                  durable design to keep your music safe and accessible.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                alt="Features"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-gray-900 dark:text-gray-50">High-Capacity Storage</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Store thousands of your favorite songs on our high-capacity music flash drives.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-gray-900 dark:text-gray-50">Lightning-Fast Transfers</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Enjoy blazing-fast data transfer speeds to quickly load your music onto any device.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-gray-900 dark:text-gray-50">Durable Design</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Our sleek, metal-cased drives are built to withstand the rigors of everyday use.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter text-gray-900 sm:text-4xl md:text-5xl dark:text-gray-50">
                What Our Customers Say
              </h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Hear from real customers who have experienced the quality and convenience of our music flash drives.
              </p>
            </div>
            <Carousel
              className="w-full max-w-4xl"
              opts={{
                align: "center",
              }}
            >
              <CarouselContent>
                <CarouselItem>
                  <Card className="bg-white dark:bg-gray-950">
                    <CardContent className="p-6">
                      <div className="space-y-4">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <img
                              alt="Avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div>
                              <h4 className="font-semibold text-gray-900 dark:text-gray-50">Jane Doe</h4>
                              <p className="text-sm text-gray-500 dark:text-gray-400">Music Enthusiast</p>
                            </div>
                          </div>
                          <div className="flex items-center gap-1 text-yellow-500">
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                          </div>
                        </div>
                        <p className="text-gray-500 dark:text-gray-400">
                          "I absolutely love my music flash drive from Music\n Drives. The storage capacity is
                          incredible, and the\n transfer speeds are lightning-fast. It's the perfect\n solution for my
                          music collection."
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </CarouselItem>
                <CarouselItem>
                  <Card className="bg-white dark:bg-gray-950">
                    <CardContent className="p-6">
                      <div className="space-y-4">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <img
                              alt="Avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div>
                              <h4 className="font-semibold text-gray-900 dark:text-gray-50">John Smith</h4>
                              <p className="text-sm text-gray-500 dark:text-gray-400">Music Producer</p>
                            </div>
                          </div>
                          <div className="flex items-center gap-1 text-yellow-500">
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                          </div>
                        </div>
                        <p className="text-gray-500 dark:text-gray-400">
                          "As a music producer, I need reliable and high-quality\n storage for my projects. The Music
                          Drives flash drive\n has exceeded my expectations. The build quality is\n impressive, and the
                          performance is outstanding."
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </CarouselItem>
                <CarouselItem>
                  <Card className="bg-white dark:bg-gray-950">
                    <CardContent className="p-6">
                      <div className="space-y-4">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <img
                              alt="Avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div>
                              <h4 className="font-semibold text-gray-900 dark:text-gray-50">Sarah Lee</h4>
                              <p className="text-sm text-gray-500 dark:text-gray-400">Music Lover</p>
                            </div>
                          </div>
                          <div className="flex items-center gap-1 text-yellow-500">
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                            <StarIcon className="h-5 w-5" />
                          </div>
                        </div>
                        <p className="text-gray-500 dark:text-gray-400">
                          "I'm so impressed with my Music Drives flash drive.\n The sound quality is amazing, and the
                          device is so\n compact and easy to use. It's the perfect companion\n for my music collection."
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </CarouselItem>
              </CarouselContent>
              <CarouselPrevious />
              <CarouselNext />
            </Carousel>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-red-500 px-3 py-1 text-sm text-gray-50 dark:bg-red-400 dark:text-gray-900">
                  Pricing
                </div>
                <h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter text-gray-900 sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem] dark:text-gray-50">
                  Unlock Your Music Potential
                </h2>
                <div className="flex flex-col gap-2 min-[400px]:flex-row" />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function ChevronDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function Music2Icon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="18" r="4" />
      <path d="M12 18V2l7 4" />
    </svg>
  )
}


function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
